apiVersion: v2
name: chronograf
version: 1.1.24
appVersion: 1.10.1
description: Open-source web application written in Go and React.js that provides
  the tools to visualize your monitoring data and easily create alerting and automation
  rules.
keywords:
- chronograf
- visualizaion
- timeseries
- influxdata
- influxdb
home: https://www.influxdata.com/time-series-platform/chronograf/
engine: gotpl
